version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      test_network:
        - ipv4_address: 173.20.0.100
    ports:
      - '1883:1883'
      - '9001-9001'

  monitor:
    build:
      context: ./Monitor
      dockerfile: Dockerfile
    container_name: seas_monitor
    restart: always
    networks:
      test_network:
        - ipv4_address: 173.20.0.101
    depends_on:
      - mosquitto

  analyzer:
    build:
      context: ./Analyzer
    # altri eventuali parametri

  planner:
    build:
      context: ./Planner
    # altri eventuali parametri

  executor:
    build:
      context: ./Executor
    # altri eventuali parametri

  managed_resources:
    build:
      context: ./ManagedResources
    # altri eventuali parametri