version: '7.0.0'

services:

  #Message Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container_test
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      - test_network
    ports:
      - '1883:1883'
      - '9001-9001'

  monitor:
    build:
      context: ./Monitor
      dockerfile: Dockerfile
    container_name: seas_monitor_test
    restart: always
    networks:
      - test_network
    depends_on:
      - mosquitto

  analyzer:
    build:
      context: ./Analyzer
      dockerfile: Dockerfile
    container_name: seas_analyzer_test
    restart: always
    networks:
      - test_network
    depends_on:
      - mosquitto

  planner:
    build:
      context: ./Planner
      dockerfile: Dockerfile
    container_name: seas_analyzer_test
    restart: always
    networks:
      - test_network
    depends_on:
      - mosquitto

  executor:
    build:
      context: ./Executor
      dockerfile: Dockerfile
    container_name: seas_executor_test
    restart: always
    networks:
      - test_network
    depends_on:
      - mosquitto

  managed_resources:
    build:
      context: ./ManagedResources
      dockerfile: Dockerfile
    container_name: seas_resources_test
    restart: always
    networks:
      - test_network
    depends_on:
      - mosquitto

networks:
  test_network: